### ISSUE TITLE
GraviChest

### ISSUE THREAD

**Issue by importnil** [estebes/Gravitation-Suite-Reloaded#1]
Hi,
This is a great upgrade for an old GraviSuite. But am I missing GraviChest?

Also as far as I see it's only possible to gather energy from lappacks and not even an advanced nanochest.

2) Would it also be possible to switch modes on some drills (like Big Diamond & Iridium)? It was also a great feature of an old GS.

Anyways thanks for this!

**Comment by estebes** [comment]
You are missing it because it still isn't implemented. Gravichestplate will be added in version 1.0 which should come out some time this week. As far as modes maybe ill change that. Its kind of a balance thing so its still work in progress.
