### ISSUE TITLE
Unable to determine registrant mod

### ISSUE THREAD

**Issue by Tsyklop** [estebes/Gravitation-Suite-Reloaded#3]
Error in the log: http://pastebin.com/panmbAya

GraviSuite_Reloaded-1.7.10-0.9.1

**Comment by Speiger** [comment]
Whats causing that:
You register the item in the constructor in the eventhandler thats why it is crashing.
Simple fix: make a interface (my was IBootableObject) that will be called after the item got constructed.
(IBootableObject was simply a interface with a function in it which was called init and it got called after the item was registered in the gameRegistry)

**Comment by Tsyklop** [comment]
@Speiger I am not the developer of this mod

**Comment by Speiger** [comment]
@Tsyklop i know but i know the dev and i thaught maybe that helps him^^

**Comment by estebes** [comment]
this is already fixed in the new build but i still need to finish some stuff before releasing it.

**Comment by Speiger** [comment]
@estebes no problem^^"
