### ISSUE TITLE
So..big tools are removed?

### ISSUE THREAD

**Issue by tytannial** [estebes/Gravitation-Suite-Reloaded#8]
New version no recipe for them. What happened?

**Comment by leagris** [comment]
Missing from release: GraviSuite_Reloaded-1.7.10-special.jar
GraviSuiteReloaded:ItemToolTheThingamabob
GraviSuiteReloaded:ItemMiscQuantumCircuit
GraviSuiteReloaded:ItemArmorQuantumLappack
GraviSuiteReloaded:ItemToolTheChopper
GraviSuiteReloaded:ItemToolBigIridiumDrill
GraviSuiteReloaded:ItemToolBigMiningDrill
GraviSuiteReloaded:ItemArmorLappack
GraviSuiteReloaded:ItemToolBigDiamondDrill

and Vajra

**Comment by tytannial** [comment]
...Maybe those items need a code upgrade

**Comment by estebes** [comment]
The special version is not for normal use. It was for people complaining about normal gravisuite jetpacks hover mode until chocohead fixed them.
